services:
  whisper:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "43001:43001"
    volumes:
      - model_data:/models

volumes:
  model_data:
